### ISSUE TITLE
Update README to reflect current state of Mantl integration

### ISSUE THREAD

**Issue by langston-barrett** [CiscoCloud/mantl-api#18]
The README currently describes how to install mantl-api on Mantl, without discussion of how it currently works, i.e. not on port 4001, but behind :80/api/.

**Comment by feliperfmarques** [comment]
Yeah. I have doubts about this. +1

**Comment by ryane** [comment]
#24 has some updates to the readme. does this clarify things or is something still missing?

**Comment by langston-barrett** [comment]
LGTM :+1:
