### ISSUE TITLE
No way to install local packages.

### ISSUE THREAD

**Issue by corebug** [CiscoCloud/mantl-api#21]
Currently there is no possibility to specify local repo/package for Mantl API to install it.
I'm currently working on adding this functionality.

@ryane do you have any comments about this?

**Comment by ryane** [comment]
What do you mean by local packages? It does currently support loading packages from a repository on the file system. I have some work in progress to make that configurable (right now it requires a rebuild). Is that what you are looking for or is there another use case you are thinking about?

**Comment by ryane** [comment]
@corebug see #23. will that solve the problem?

**Comment by corebug** [comment]
@ryane yeah, looks great. I'm closing the issue by now, thank you.
