### ISSUE TITLE
Inconsistencies with \install or \installs 

### ISSUE THREAD

**Issue by jtfogarty** [CiscoCloud/mantl-api#32]
To install a package is the uri /install or installs ?  I see both on this page

https://github.com/CiscoCloud/mantl-api#usage

but neither work

**Comment by ryane** [comment]
I updated the readme with the correct url (/install). Sorry about that; thanks for pointing it out. /install should work but only if you are using the latest version (0.1.4, see #13). Previous versions used /packages for install/uninstall.

**Comment by ryane** [comment]
this has been updated in the docs. let me know if you still see any issues
