### ISSUE TITLE
UI for installing / removing packages

### ISSUE THREAD

**Issue by BrianHicks** [CiscoCloud/mantl-api#9]
The UI should:
- [ ] show health (`/health`)
- [ ] present a list of packages, listing installed state for each (`/1/packages`)
- [ ] allow filtering unsupported packages (`/1/packages`)
- [ ] install a package (`POST /1/packages`)
- [ ] uninstall a package (`DELETE /1/packages`)
- [ ] get all the details about a package (`/1/packages/{name}`)

**Comment by BrianHicks** [comment]
This turns out to be https://github.com/CiscoCloud/mantl-ui-frontend. And Health is already completed.

**Comment by ryane** [comment]
moved to CiscoCloud/mantl-ui-frontend#5
